### PR TITLE
Refactor authority startup with cobra and viper

### PR DESCRIPTION
**Pull request by 2456868764**
## What is the purpose of the change

Refactor authority startup with cobra and viper

## Brief changelog
1.  change authority command line flags style as follow: 

 ./authority --help
The authority app is responsible for controllers in dubbo authority

Usage:
  authority [flags]

Flags:
      --debug-port int            dubbo debug port (default 30070)
      --enable-oidc-check         dubbo enable OIDC check
  -h, --help                      help for authority
      --in-pod-env                dubbo run in pod environment
      --is-kubernetes-connected   dubbo connected with kubernetes
      --kubeconfig string         Paths to a kubeconfig. Only required if out-of-cluster.
      --namespace string          dubbo namespace (default "dubbo-system")
      --plain-server-port int     dubbo plain server port (default 30060)
      --secure-server-port int    dubbo secure server port (default 30062)
      --service-name string    dubbo service name (default "dubbo-ca")
      --webhook-allow-on-err      dubbo webhook allow on error (default true)
      --webhook-port int32        dubbo webhook port (default 30080)

2. Read  command line flags from Env variables, which are prefixed with DUBBO , for example

DUBBO_PLAIN_SERVER_PORT

3. Change k8s client init rest.config 

               `// Read kubeconfig from command line
		if len(kubeconfig) <= 0 {
			// Read kubeconfig from env
			kubeconfig = os.Getenv(clientcmd.RecommendedConfigPathEnvVar)
			if len(kubeconfig) <= 0 {
				// Read kubeconfig from home dir
				if home := homedir.HomeDir(); home != "" {
					kubeconfig = filepath.Join(home, ".kube", "config")
				}
			}
		}`

## Verifying this change
1.  ./authority 
2.  ./authority --kubeconfig=/Users/jun/.kube/config_kind  --plain-server-port=30061
3.  DUBBO_PLAIN_SERVER_PORT=30061; ./authority
4.  KUBECONFIG=/Users/jun/.kube/config_kind;DUBBO_PLAIN_SERVER_PORT=30069; ./authority --plain-server-port=30061

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist.
* [ ] Run `mvn clean compile --batch-mode -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true to make sure basic checks pass.

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Please fix conflicts

**Comment by 2456868764** [comment]
> Please fix conflicts

i've fixed the conflicts and merged envflag.go , pls review it again!

**Review by AlbumenJ — APPROVED** [review]
LGTM
Please fix conflict again :)

**Comment by 2456868764** [comment]
> LGTM Please fix conflict again :)

I've fixed the conflict, please review again

**Pull request merged**
