### PR TITLE
[DUBBO-ADMIN-198]: Support multiple registry centers

### LINKED ISSUE #198: multi registry support
Any idea?

### PR DESCRIPTION
**Pull request by kezhenxu94**
resolves #198

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Hi @nzomkxia , according what you said in [comment](https://github.com/apache/incubator-dubbo-ops/issues/198#issuecomment-465434340), I've just updated this PR, I've tested it like this:

- modify the `dubbo-provider.xml` in [dubbo-demo](https://github.com/nzomkxia/dubbo-demo) as follows to register services in multiple registry centers:
```xml

    <!-- provider's application name, used for tracing dependency relationship -->
    <dubbo:application name="meetup-demo-provider"/>

    <dubbo:registry address="zookeeper://127.0.0.1:2181" id="reg1"/>
    <dubbo:registry address="zookeeper://127.0.0.1:2182" id="reg2"/>

    <!-- use dubbo protocol to export service on port 20880 -->
    <dubbo:protocol name="dubbo" port="20880"/>

    <!-- service implementation, as same as regular local bean -->
    <!--<bean id="demoService" class="org.apache.dubbo.demo.impl.DemoServiceImpl"/>-->
    <!--<bean id="userService" class="org.apache.dubbo.demo.impl.UserServiceImpl"/>-->
    <!--<bean id="timeoutTestService" class="org.apache.dubbo.demo.impl.TimeoutTestServiceImpl"/>-->
    <!--<bean id="noResponseService" class="org.apache.dubbo.demo.impl.NoResponseServiceImpl"/>-->

    <!-- declare the service interface to be exported -->
    <dubbo:service registry="reg1" interface="org.apache.dubbo.demo.api.DemoService" ref="demoService"/>
    <dubbo:service registry="reg1" interface="org.apache.dubbo.demo.api.UserService" ref="userService"/>
    <dubbo:service registry="reg1" interface="org.apache.dubbo.demo.api.TimeoutTestService" ref="timeoutTestService"/>
    <dubbo:service registry="reg2" interface="org.apache.dubbo.demo.api.NoResponseService" ref="noResponseService"/>
    <dubbo:service registry="reg2" interface="org.apache.dubbo.demo.api.NoResponse2Service" ref="noResponse2Service"/>
```
and start the providers

- open the OPS and search the services, all the services in different registry center are shown, here is the screenshot:
image

I'm wondering if I misunderstood your saying, please let me know if I missed anything, thanks

**Comment by kexianjun** [comment]
I think if we support multiple registry center, it's necessary to make it clear which registry cneter that the service belongs to.

**Comment by kezhenxu94** [comment]
> I think if we support multiple registry center, it's necessary to make it clear which registry cneter that the service belongs to.

@kexianjun Thanks for your advice, it makes sense!! And I've updated according to your suggestion, could you please have a look when you have time :)

**Comment by heyudev** [comment]
是否支持同一服务注册到多个注册中心的情况

**Comment by CodingSinger** [comment]
why this pr  have not be merged?

**Comment by kezhenxu94** [comment]
> why this pr have not be merged?

no response

**Comment by johnsonin** [comment]
after a year, this pr still no merge.is something wrong?

**Pull request closed without merging**
