### PR TITLE
fix 404 and 500 when there are grouped services

### PR DESCRIPTION
**Pull request by mzlogin**
fix apache#61

fix apache#540

### CODE REVIEW

**Comment by mzlogin** [comment]
We are using master branch now, our dubbo services are grouped. There are some errors when running original master branch like below (some other people has met as they mentioned in #61 and #540 ):

## Case 1

image

image

Url: <http://localhost:7001/governance/services/product/com.xxxx.service.pathfinder.address.AddressService/providers>

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Nov 27 18:00:37 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
Circular view path []: would dispatch back to the current handler URL [/governance/services/product/com.xxxx.service.pathfinder.address.AddressService/] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
```

## Case 2

image

image

Url: <http://localhost:7001/governance/applications/esp-admin/addresses/10.10.60.112/consumers/consumers/55808>

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Nov 27 18:10:52 CST 2020
There was an unexpected error (type=Not Found, status=404).
No message available
```

After fix route in RouterController.java

## Case 3

image

image

Url: <http://localhost:7001/governance/applications/esp-admin/services/product/com.extendfacade.service.OperateRecordService/consumers>

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Nov 27 18:16:33 CST 2020
There was an unexpected error (type=Internal Server Error, status=500).
Circular view path []: would dispatch back to the current handler URL [/governance/applications/esp-admin/services/product/com.extendfacade.service.OperateRecordService/] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
```

This Pull Request fix these bad cases.

**Comment by KeRan213539** [comment]
Sorry, the "master" branch is an old version. We don't maintain it anymore. The latest version is in the "develop"branch.
If the "develop" branch also has this problem, you are welcome to fix it in the "develop" branch.
By the way, we will merge the "develop" branch into the "master" branch when 0.3.0 is released.
Please feel free to reopen it if you have any question.

**Comment by mzlogin** [comment]
> Sorry, the "master" branch is an old version. We don't maintain it anymore. The latest version is in the "develop"branch.
> If the "develop" branch also has this problem, you are welcome to fix it in the "develop" branch.
> By the way, we will merge the "develop" branch into the "master" branch when 0.3.0 is released.
> Please feel free to reopen it if you have any question.

I don't know if the "develop" branch also has this problem, but I have one suggestion here.

There are big differences between the "develop" branch version and the "master" branch version, the "develop" is more modern and more elegant, but the "master" is more convenient to deploy. I believe both of them can meet the demand, but for my scenario, easy deployment is more important.

I think there are many people like me. So, would you please consider that 

merge this PR and mark a tag in "master" branch 

or

archive a separate branch containing this change.

This can help other people in need. Thanks!

**Review by KeRan213539 — APPROVED** [review]
LGTM.
Later, we will create a master-0.2.0 branch based on the master branch. If there are changes to the 0.2.0 version in the future, please PR to this branch

**Pull request merged**
