### PR TITLE
Feature/dockerized dubbo admin

### PR DESCRIPTION
**Pull request by xmeng1**
Dockerize dubbo-admin to deploy easily
https://hub.docker.com/r/xinmeng/dubbo-admin/ 
docker-compse file and instruction has been included

### CODE REVIEW

**Comment by nzomkxia** [comment]
please add apache license to your new added file

**Comment by xmeng1** [comment]
hi, the licence has been added

**Comment by htynkn** [comment]
Dockerize dubbo admin is a good idea. we can have a docker hub account and let docker hub to compile code and build docker image.

**Comment by xmeng1** [comment]
@htynkn You are right, the image repository is easy to update in Maven configuration. And we can automatically update it by Travis.

**Comment by ettingshausen** [comment]
Hi, maintainers.  Months past, will this PR merge into develop branch?

**Comment by biyuhao** [comment]
This PR is against `master` branch. However, `develop` is currently our active branch.

**Comment by xmeng1** [comment]
ok, let me change the base branch to develop, is it right? @biyuhao

**Comment by biyuhao** [comment]
Hi @xmeng1 
Sorry for the late response. After a review of your work and some study of the [docker module of Apache nifi](https://github.com/apache/nifi/tree/master/nifi-docker), I have several suggestions.

- Since we have `dubbo-admin-distribution` module in the `develop` branch, I think we can put this function into that module along with other packing stuff.
- Binding with `docker` profile and `package` phase. Then we may package with this command `./mvnw clean package -Pdocker -DskipTests`
- We may have to use `Apache Dubbo <dev@dubbo.apache.org>` for `maintainer` in `Dockerfile`. Please refer to https://github.com/apache/nifi/blob/master/nifi-docker/dockermaven/Dockerfile#L20
- Seems the ASF do have a [official dockerhub account](https://hub.docker.com/u/apache) and there are already some repos here. Dubbo is still under incubation I'm not sure if we can publish to the official account. (Need some guide from PPMC)

any advice is welcome

**Comment by ettingshausen** [comment]
> * Binding with `docker` profile and `package` phase. Then we may package with this command `./mvnw clean package -Pdocker -DskipTests`    

Hi, @biyuhao I agree with your suggestions. 
However considering users who don’t have Docker installed, they run `mvn package` will get an error. Building an image should not be a common operation I think.  So I recommend not binding the compilation phase. Let users build images on their demand. With `mvn dockerfile:build` or `mvn dockerfile:push` .

**Comment by biyuhao** [comment]
@ettingshausen Yes, I have noticed that.
We can add a maven profile just like the `release` profile we used. https://github.com/apache/incubator-dubbo-ops/blob/develop/dubbo-admin-distribution/pom.xml#L69
The `gpg sign` and `bin-release` action is executed only if you enable the `release` profile. (specify with `-Prelease`) Many users didn't setup `gpg` environment either.

For the better convenience, I prefer to use `-Pdocker`.
I hope this looks good to you :)

**Comment by ralf0131** [comment]
> Hi @xmeng1

> Sorry for the late response. After a review of your work and some study of the [docker module of Apache nifi](https://github.com/apache/nifi/tree/master/nifi-docker), I have several suggestions.
> 
> * Since we have `dubbo-admin-distribution` module in the `develop` branch, I think we can put this function into that module along with other packing stuff.

+1

> * Binding with `docker` profile and `package` phase. Then we may package with this command `./mvnw clean package -Pdocker -DskipTests`

+1 

> * We may have to use `Apache Dubbo <dev@dubbo.apache.org>` for `maintainer` in `Dockerfile`. Please refer to https://github.com/apache/nifi/blob/master/nifi-docker/dockermaven/Dockerfile#L20

+1

> * Seems the ASF do have a [official dockerhub account](https://hub.docker.com/u/apache) and there are already some repos here. Dubbo is still under incubation I'm not sure if we can publish to the official account. (Need some guide from PPMC)

Yes, we can.

> 
> any advice is welcome

**Comment by nzomkxia** [comment]
the docker image has been intergrated in #356

**Pull request closed without merging**
